"""
Standalone 17-Joint to 64-Marker TRC Adapter Trainer
======================================================
Trains a lightweight PyTorch model to map 17-joint 3D skeletons
(such as those generated by MotionBERT) into a dense 64-marker TRC format.

Usage:
    python3 train_17_to_64_adapter.py
"""

import sys
import os
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import pandas as pd
import numpy as np
import glob

# ==========================================
# 1. THE ADAPTER MODEL
# ==========================================
class Adapter17to64(nn.Module):
    def __init__(self, in_features=51, hidden_dim=256, out_features=192):
        super(Adapter17to64, self).__init__()
        
        # 17 joints * 3 coords = 51 in
        # 64 markers * 3 coords = 192 out
        self.net = nn.Sequential(
            nn.Linear(in_features, hidden_dim),
            nn.LayerNorm(hidden_dim),
            nn.GELU(),
            nn.Dropout(0.1),
            nn.Linear(hidden_dim, hidden_dim),
            nn.LayerNorm(hidden_dim),
            nn.GELU(),
            nn.Linear(hidden_dim, out_features)
        )
        
        # Initialize weights
        for m in self.net.modules():
            if isinstance(m, nn.Linear):
                nn.init.xavier_uniform_(m.weight)
                nn.init.zeros_(m.bias)

    def forward(self, x):
        # x shape: (Batch, SeqLen, 51) or (Batch, 51)
        return self.net(x)

# ==========================================
# 2. THE DATASET (Synthesizes 17-joint input from 64-marker TRC)
# ==========================================
class TRCAdapterDataset(Dataset):
    """
    Loads real 64-marker 3D TRC data.
    Synthesizes the corresponding 17-joint 3D input that MotionBERT would output.
    Returns pairs of: (17_joint_3d_vector, 64_marker_3d_vector)
    """
    def __init__(self, trc_folder, noise_std=0.005):
        self.noise_std = noise_std
        self.x_data = [] # Will be (N, 51)
        self.y_data = [] # Will be (N, 192)
        
        # These are the TRC marker indices (0-63) that correspond to each of the 17 H36M joints
        # 0: Pelvis -> midpoint of 1 and 2
        # 1: R Hip -> 38, 2: R Knee -> 39, 3: R Ankle -> 46
        # 4: L Hip -> 42, 5: L Knee -> 43, 6: L Ankle -> 49
        # 7: Spine -> 14, 8: Neck -> 15
        # 9: Nose -> 19, 10: Head -> 16
        # 11: L Shoulder -> 21, 12: L Elbow -> 24, 13: L Wrist -> 29
        # 14: R Shoulder -> 20, 15: R Elbow -> 22, 16: R Wrist -> 26
        
        self.h36m_mapping = {
            1: 38, 2: 39, 3: 46,
            4: 42, 5: 43, 6: 49,
            7: 14, 8: 15, 9: 19, 10: 16,
            11: 21, 12: 24, 13: 29,
            14: 20, 15: 22, 16: 26
        }
        
        trc_files = glob.glob(os.path.join(trc_folder, "**", "*.trc"), recursive=True)
        print(f"Synthesizing 17-to-64 training data from {len(trc_files)} TRC files...")
        
        for file in trc_files:
            try:
                df = pd.read_csv(file, sep='\t', skiprows=6, header=None)
                coords = df.iloc[:, 2:194].interpolate(axis=0).fillna(0.0).values.astype(np.float32)
                coords = coords / 1000.0  # mm to meters
                
                num_frames = coords.shape[0]
                
                # Hip centering (per frame)
                for f_idx in range(num_frames):
                    hip_x, hip_y, hip_z = coords[f_idx, 0:3]
                    for i in range(0, 192, 3):
                        coords[f_idx, i]   -= hip_x
                        coords[f_idx, i+1] -= hip_y
                        coords[f_idx, i+2] -= hip_z
                
                # Extract 17-joint input (17 * 3 = 51)
                inputs_17j = np.zeros((num_frames, 51), dtype=np.float32)
                for f_idx in range(num_frames):
                    # Joint 0: Pelvis (midpoint of TRC 1 and 2)
                    inputs_17j[f_idx, 0:3] = (coords[f_idx, 1*3:1*3+3] + coords[f_idx, 2*3:2*3+3]) / 2.0
                    
                    # Rest of joints
                    for j_idx, trc_marker in self.h36m_mapping.items():
                        inputs_17j[f_idx, j_idx*3 : j_idx*3+3] = coords[f_idx, trc_marker*3 : trc_marker*3+3]
                
                # Add noise to simulate slightly imperfect MotionBERT predictions
                noise = np.random.normal(0, self.noise_std, inputs_17j.shape).astype(np.float32)
                inputs_17j += noise
                
                self.x_data.append(inputs_17j)
                self.y_data.append(coords)
                    
            except Exception as e:
                pass
        
        if len(self.x_data) > 0:
            self.x_data = np.concatenate(self.x_data, axis=0)
            self.y_data = np.concatenate(self.y_data, axis=0)
            print(f"Generated {self.x_data.shape[0]} training frames.")
        else:
            print("No data found.")

    def __len__(self):
        return self.x_data.shape[0]

    def __getitem__(self, idx):
        return torch.tensor(self.x_data[idx]), torch.tensor(self.y_data[idx])

# ==========================================
# 3. THE TRAINING LOOP
# ==========================================
def train_adapter(trc_folder_path, epochs=30, batch_size=256, lr=1e-3, log_every=100):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    
    print("=" * 60)
    print("  STANDALONE 17-JOINT TO 64-MARKER ADAPTER TRAINING")
    print("=" * 60)
    
    print("\n[1/3] Loading TRC dataset...")
    dataset = TRCAdapterDataset(trc_folder=trc_folder_path, noise_std=0.005)
    
    if len(dataset) == 0:
        print("❌ Dataset is empty. Aborting.")
        return
    
    dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=True, num_workers=4, pin_memory=True)
    
    print("\n[2/3] Building Adapter Model...")
    model = Adapter17to64().to(device)
    
    criterion = nn.MSELoss()
    optimizer = optim.AdamW(model.parameters(), lr=lr, weight_decay=1e-4)
    scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs)
    
    total_batches = len(dataloader)
    
    print(f"\n[3/3] Starting training on: {device}")
    print(f"   Dataset size:   {len(dataset)} frames")
    print(f"   Batch size:     {batch_size}")
    print(f"   Batches/epoch:  {total_batches}")
    print(f"   Epochs:         {epochs}")
    print("=" * 60)
    
    best_loss = float('inf')
    
    for epoch in range(epochs):
        model.train()
        total_epoch_loss = 0.0
        running_loss = 0.0
        
        for batch_idx, (batch_x, batch_y) in enumerate(dataloader):
            batch_x = batch_x.to(device)  # (B, 51)
            batch_y = batch_y.to(device)  # (B, 192)

            optimizer.zero_grad()
            outputs = model(batch_x)       # (B, 192)
            loss = criterion(outputs, batch_y)
            loss.backward()
            optimizer.step()

            loss_val = loss.item()
            total_epoch_loss += loss_val
            running_loss += loss_val

            if (batch_idx + 1) % log_every == 0 or (batch_idx + 1) == total_batches:
                avg_running = running_loss / min(log_every, batch_idx + 1)
                progress = 100. * (batch_idx + 1) / total_batches
                print(f"Epoch [{epoch+1}/{epochs}] "
                      f"Batch [{batch_idx+1:04d}/{total_batches}] "
                      f"({progress:05.1f}%) | "
                      f"Loss: {avg_running:.6f} | "
                      f"LR: {scheduler.get_last_lr()[0]:.6f}")
                running_loss = 0.0

        scheduler.step()
        avg_epoch_loss = total_epoch_loss / total_batches
        
        print("-" * 60)
        print(f"✅ Epoch {epoch+1} complete | Avg Loss: {avg_epoch_loss:.6f}")
        
        # Save best model
        if avg_epoch_loss < best_loss:
            best_loss = avg_epoch_loss
            torch.save(model.state_dict(), "adapter_17_to_64_best.pth")
            print(f"💾 New best! Saved to adapter_17_to_64_best.pth (Loss: {best_loss:.6f})")
        print("=" * 60)

    # Final save
    torch.save(model.state_dict(), "adapter_17_to_64_final.pth")
    print(f"\n💾 Final weights saved to adapter_17_to_64_final.pth")
    print(f"🏆 Best loss achieved: {best_loss:.6f}")

# ==========================================
# 4. EXECUTION
# ==========================================
if __name__ == "__main__":
    train_adapter(
        trc_folder_path="data/motionsdata",
        epochs=30,
        batch_size=256,
        lr=1e-3,
        log_every=50
    )
